### ISSUE TITLE
Sudo rfcomm bind, missing dev parameter

### ISSUE THREAD

**Issue by Luke-Gilbert** [ivanmorenoj/rpi-bluetooth-arduino#1]
Readme.md
 
When creating a serial device, sudo rfcomm bind xx:xx:xx:xx:xx:xx, says missing dev parameter.
You need to run sudo rfcomm bind /dev/rfcom0 xx:xx:xx:xx:xx:xx instead.
Of course replace rfcom0 if that address isn't free.

**Comment by ivanmorenoj** [comment]
Hi, in the tutorial i wrote `sudo rfcomm bind rfcomm0 <device's MAC>`.  I tried again and it woks perfectly.
